apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpcgoonch-headless-long-client-roundrobin-cronjob
  labels:
    app: grpcgoonch-headless-long-client-roundrobin
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grpcgoonch-headless-long-client-roundrobin
    spec:
      template:
        spec:
          containers:
          - name: grpcgoonch-headless-long-client-roundrobin
            image: grpcgoonch-headless-long-client-roundrobin:1.0
            imagePullPolicy: IfNotPresent
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"